// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5OXVlbF-Ie8FFR7luZlwVreFwBNx6eg',
    appId: '1:709086117435:android:b8ec7dfe1d00f9ebfe261e',
    messagingSenderId: '709086117435',
    projectId: 'home-ai-3a75c',
    storageBucket: 'home-ai-3a75c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGo1AQM2zxzIe1dexGc2SqW1WfbsnIXQ',
    appId: '1:709086117435:ios:31b5c38e54bd661cfe261e',
    messagingSenderId: '709086117435',
    projectId: 'home-ai-3a75c',
    storageBucket: 'home-ai-3a75c.firebasestorage.app',
    iosClientId: '709086117435-s6bsjrk7cb9tkb5lcdjf7jk3qrl215pk.apps.googleusercontent.com',
    iosBundleId: 'com.gnetsol.interiorDesignerJasper',
  );
}
